### ISSUE TITLE
Dependency Error: org.grails.plugins:spring-security-facebook:0.18 FAILED

### ISSUE THREAD

**Issue by mxgross** [splix/grails-facebook-authentication-example#10]
Where can I get the Version 0.18? It seems to be missing in the repo from https://repo.grails.org/grails/core?

**Comment by splix** [comment]
Oh, sorry. Example app is already upgraded to new plugin, which is not released to central repo yet.

You could try to clone [plugin](https://github.com/splix/grails-spring-security-facebook) and make `gradle install` locally, if you don't want to wait. 

Or if you _don't need Grails 3_, you can try with previous version of the example app, just go one commit back (to [72092a76bc53af7]).
